name: My App
targets:
  My App:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [My App, Resources]
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.AppInstalleriOS.My-App
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
